# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('tasks', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('owners', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
