# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20160425_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='incomplete',
            field=models.BooleanField(default=True),
        ),
    ]
