# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancelists', '0002_auto_20160427_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
