# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=200)),
                ('postDate', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
    ]
