# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarbulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['-postDate']},
        ),
    ]
