# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarbulletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinClearer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_check', models.DateTimeField(default=datetime.datetime(2016, 4, 2, 18, 24, 23, 866809))),
            ],
            options={
                'ordering': ['-last_check'],
            },
        ),
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['-postDate']},
        ),
        migrations.AddField(
            model_name='bulletin',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 18, 24, 23, 866809)),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 18, 24, 23, 866809), editable=False),
        ),
    ]
