# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calendarbulletin', '0005_auto_20160402_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 22, 56, 21, 823261, tzinfo=utc)),
        ),
    ]
