# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calendarbulletin', '0008_auto_20160402_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2016, 4, 12, 23, 30, 6, 956547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bulletinclearer',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 23, 30, 6, 956547, tzinfo=utc)),
        ),
    ]
