# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarbulletin', '0002_auto_20160406_1531'),
        ('calendarbulletin', '0011_auto_20160406_1634'),
    ]

    operations = [
    ]
