# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarbulletin', '0014_auto_20160425_2001'),
        ('calendarbulletin', '0013_auto_20160407_1847'),
    ]

    operations = [
    ]
