# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarbulletin', '0017_auto_20160427_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2016, 5, 8)),
        ),
        migrations.AlterField(
            model_name='bulletinclearer',
            name='last_check',
            field=models.DateField(default=datetime.date(2016, 4, 18)),
        ),
    ]
